// The security test for the subscribe/confirm/unsubscribe token. RUN IT BEFORE
// PUBLISHING, and re-run it after any change to _subscribe_token.js.
//
//   . stack/commons/public/bin/node-env.sh
//   cd stack/commons/public && node functions/api/_subscribe_token.test.mjs
//
// WHY THIS FILE EXISTS
//
// The token is the only thing standing between a stranger and the chapter's
// mailing lists, and it is a primitive this codebase had no precedent for. So
// it gets adversarial tests rather than a comment saying it looked right.
//
// It is also the INTEROP CONTRACT. The two Python senders mint their own
// List-Unsubscribe tokens with hmac/hashlib, and if the two implementations
// ever disagree by one byte, every unsubscribe link in the chapter's mail stops
// working silently. The vectors in section 1 were generated by the Python
// reference implementation printed in the header of _subscribe_token.js and are
// asserted here against the shipped JavaScript, so the two cannot drift without
// this failing.

import {
  PURPOSE_CONFIRM,
  PURPOSE_UNSUB,
  TOKEN_VERSION,
  b64urlDecode,
  b64urlEncode,
  isPlausibleEmail,
  mintToken,
  normalizeEmail,
  verifyToken,
} from './_subscribe_token.js';
import { LIST_SLUGS, NEWS_MODES, entriesFromClaims } from './_lists.js';
import { onRequestPost as subscribePost } from './subscribe.js';
import { onRequestGet as confirmGet } from './confirm.js';

let failures = 0;
const check = (label, ok, detail = '') => {
  if (!ok) {
    failures += 1;
    console.error(`  FAIL  ${label}${detail ? `: ${detail}` : ''}`);
  }
};

// Not a credential. A published test vector, kept deliberately obvious so
// nobody mistakes it for the real SUBSCRIBE_HMAC_KEY, which exists only as a
// Cloudflare Pages secret and never in this repo.
const TEST_SECRET = 'knoxdsa-test-vector-not-a-real-value';
const ALLOWED = LIST_SLUGS;

const enc = new TextEncoder();

// --- 1. cross-language known-answer vectors --------------------------------
// Produced by Python:
//   payload = base64url(json.dumps(claims, separators=(",", ":")).encode())
//   sig     = base64url(hmac.new(secret.encode(), payload.encode("ascii"),
//                                hashlib.sha256).digest())
// with "=" padding stripped from both.

const VECTOR_UNSUB =
  'eyJ2IjoxLCJwIjoidW5zdWIiLCJlIjoibmVpZ2hib3JAZXhhbXBsZS5vcmciLCJpIjpbXSwi' +
  'byI6WyJsZWdpc2xhdGl2ZSJdLCJ0IjoxNzUzNjYwODAwLCJ4IjowLCJuIjoiQUFBQUFBQUFB' +
  'QUFBQUFBQUFBQUFBQSJ9.vMRSvSHep5KEyLfOOISMry1WAd5DXAz_nAK2hg4FxMo';

const VECTOR_CONFIRM =
  'eyJ2IjoxLCJwIjoiY29uZmlybSIsImUiOiJuZWlnaGJvckBleGFtcGxlLm9yZyIsImkiOlsi' +
  'bGVnaXNsYXRpdmUiLCJuZXdzLXBhc3NpdmUiXSwibyI6WyJuZXdzLWFnZ3Jlc3NpdmUiXSwi' +
  'dCI6MTc1MzY2MDgwMCwieCI6MTc1MzgzMzYwMCwibiI6IkFBQUFBQUFBQUFBQUFBQUFBQUFB' +
  'QUEifQ.kl2RB2Jfq40vXRgF_6NVomC5vRP6o9VM1qMxtMuBge0';

const ISSUED = 1753660800;

{
  const r = await verifyToken(TEST_SECRET, VECTOR_UNSUB, {
    purpose: PURPOSE_UNSUB,
    allowed: ALLOWED,
    now: ISSUED + 60,
  });
  check('python-minted unsub token verifies in javascript', r.ok, r.reason);
  if (r.ok) {
    check('vector email', r.claims.email === 'neighbor@example.org');
    check('vector opt-in empty', r.claims.optIn.length === 0);
    check('vector opt-out is exactly legislative',
          r.claims.optOut.length === 1 && r.claims.optOut[0] === 'legislative');
    check('vector never expires', r.claims.expires === 0);
  }
}
{
  const r = await verifyToken(TEST_SECRET, VECTOR_CONFIRM, {
    purpose: PURPOSE_CONFIRM,
    allowed: ALLOWED,
    now: ISSUED + 60,
  });
  check('python-minted confirm token verifies in javascript', r.ok, r.reason);
  if (r.ok) {
    check('vector opt-in carries both lists',
          r.claims.optIn.join(',') === 'legislative,news-passive');
    check('vector opt-out carries the unpicked news mode',
          r.claims.optOut.join(',') === 'news-aggressive');
    check('vector expiry is 48h after issue',
          r.claims.expires === ISSUED + 48 * 3600);
  }
}

// The vectors must be rejected under any other key. If this passes with the
// wrong secret the whole scheme is decorative.
{
  const r = await verifyToken(`${TEST_SECRET}x`, VECTOR_UNSUB, {
    purpose: PURPOSE_UNSUB, allowed: ALLOWED, now: ISSUED + 60,
  });
  check('a vector does not verify under a different key',
        !r.ok && r.reason === 'bad_signature', r.reason);
}

// --- 2. round trip ----------------------------------------------------------
const confirmToken = await mintToken(TEST_SECRET, {
  purpose: PURPOSE_CONFIRM,
  email: '  Neighbor@Example.ORG ',
  optIn: ['legislative'],
  optOut: [],
  allowed: ALLOWED,
  now: ISSUED,
});
{
  const r = await verifyToken(TEST_SECRET, confirmToken, {
    purpose: PURPOSE_CONFIRM, allowed: ALLOWED, now: ISSUED + 10,
  });
  check('mint/verify round trip', r.ok, r.reason);
  check('email is normalized at mint', r.ok && r.claims.email === 'neighbor@example.org');
  check('version is pinned', r.ok && r.claims.version === TOKEN_VERSION);
  check('nonce is present and 22 chars of base64url',
        r.ok && /^[A-Za-z0-9_-]{22}$/.test(r.claims.nonce));
}
check('two mints of the same request differ',
      confirmToken !== await mintToken(TEST_SECRET, {
        purpose: PURPOSE_CONFIRM, email: 'neighbor@example.org',
        optIn: ['legislative'], optOut: [], allowed: ALLOWED, now: ISSUED,
      }));

const unsubToken = await mintToken(TEST_SECRET, {
  purpose: PURPOSE_UNSUB,
  email: 'neighbor@example.org',
  optIn: [],
  optOut: ['legislative'],
  allowed: ALLOWED,
  now: ISSUED,
});

// --- 3. forgery -------------------------------------------------------------
const [goodPayload, goodSig] = confirmToken.split('.');

check('an unsigned payload is refused',
      !(await verifyToken(TEST_SECRET, goodPayload, {
        purpose: PURPOSE_CONFIRM, allowed: ALLOWED, now: ISSUED + 10 })).ok);

check('an empty signature is refused',
      !(await verifyToken(TEST_SECRET, `${goodPayload}.`, {
        purpose: PURPOSE_CONFIRM, allowed: ALLOWED, now: ISSUED + 10 })).ok);

check('a third segment is refused',
      !(await verifyToken(TEST_SECRET, `${confirmToken}.extra`, {
        purpose: PURPOSE_CONFIRM, allowed: ALLOWED, now: ISSUED + 10 })).ok);

// Swap the payload for one naming a different address, keeping a real signature.
{
  const forged = b64urlEncode(enc.encode(JSON.stringify({
    v: 1, p: 'confirm', e: 'attacker@example.net', i: ['legislative'], o: [],
    t: ISSUED, x: ISSUED + 3600, n: 'AAAAAAAAAAAAAAAAAAAAAA',
  })));
  const r = await verifyToken(TEST_SECRET, `${forged}.${goodSig}`, {
    purpose: PURPOSE_CONFIRM, allowed: ALLOWED, now: ISSUED + 10,
  });
  check('a swapped payload with a real signature is refused',
        !r.ok && r.reason === 'bad_signature', r.reason);
}

// Flip one character of the signature.
{
  const flipped = goodSig[0] === 'A' ? `B${goodSig.slice(1)}` : `A${goodSig.slice(1)}`;
  check('a one character signature change is refused',
        !(await verifyToken(TEST_SECRET, `${goodPayload}.${flipped}`, {
          purpose: PURPOSE_CONFIRM, allowed: ALLOWED, now: ISSUED + 10 })).ok);
}

// A signature of the wrong length must never be accepted, however it is padded.
check('a truncated signature is refused',
      !(await verifyToken(TEST_SECRET, `${goodPayload}.${goodSig.slice(0, 20)}`, {
        purpose: PURPOSE_CONFIRM, allowed: ALLOWED, now: ISSUED + 10 })).ok);

for (const junk of ['', '.', '..', 'a.b', 'not a token', '%%%.%%%', `${goodPayload}.$$$`]) {
  check(`junk input ${JSON.stringify(junk)} is refused`,
        !(await verifyToken(TEST_SECRET, junk, {
          purpose: PURPOSE_CONFIRM, allowed: ALLOWED, now: ISSUED + 10 })).ok);
}

check('an absent signing key refuses rather than accepts',
      !(await verifyToken('', confirmToken, {
        purpose: PURPOSE_CONFIRM, allowed: ALLOWED, now: ISSUED + 10 })).ok);

// --- 4. purpose confinement -------------------------------------------------
check('a confirm token is refused at the unsubscribe endpoint',
      !(await verifyToken(TEST_SECRET, confirmToken, {
        purpose: PURPOSE_UNSUB, allowed: ALLOWED, now: ISSUED + 10 })).ok);
check('an unsub token is refused at the confirm endpoint',
      !(await verifyToken(TEST_SECRET, unsubToken, {
        purpose: PURPOSE_CONFIRM, allowed: ALLOWED, now: ISSUED + 10 })).ok);
{
  const r = await verifyToken(TEST_SECRET, unsubToken, {
    purpose: PURPOSE_CONFIRM, allowed: ALLOWED, now: ISSUED + 10,
  });
  check('the refusal names the purpose mismatch', r.reason === 'wrong_purpose', r.reason);
}

// --- 5. list confinement ----------------------------------------------------
// The property the whole design turns on: a Legislative Watch link cannot touch
// News Watch.
{
  const r = await verifyToken(TEST_SECRET, unsubToken, {
    purpose: PURPOSE_UNSUB, allowed: ALLOWED, now: ISSUED + 10,
  });
  const entries = entriesFromClaims(r.claims);
  check('an unsub token yields exactly one resend change', entries.length === 1);
  check('and it is an opt_out on the one list it names',
        entries[0].slug === 'legislative' && entries[0].subscription === 'opt_out');
  for (const mode of NEWS_MODES) {
    check(`the legislative unsub token never mentions ${mode}`,
          !entries.some((e) => e.slug === mode));
  }
}

// An unsub token must name exactly one list. Two is refused even when signed.
for (const bad of [
  { purpose: PURPOSE_UNSUB, optIn: [], optOut: ['legislative', 'news-passive'] },
  { purpose: PURPOSE_UNSUB, optIn: [], optOut: [] },
  { purpose: PURPOSE_UNSUB, optIn: ['legislative'], optOut: ['news-passive'] },
  { purpose: PURPOSE_CONFIRM, optIn: [], optOut: ['legislative'] },
  { purpose: PURPOSE_CONFIRM, optIn: ['legislative'], optOut: ['legislative'] },
  { purpose: PURPOSE_CONFIRM, optIn: ['legislative', 'legislative'], optOut: [] },
  { purpose: PURPOSE_CONFIRM, optIn: ['not-a-list'], optOut: [] },
]) {
  let threw = false;
  try {
    await mintToken(TEST_SECRET, { ...bad, email: 'neighbor@example.org', allowed: ALLOWED });
  } catch {
    threw = true;
  }
  check(`mint refuses ${bad.purpose} in=[${bad.optIn}] out=[${bad.optOut}]`, threw);
}

// The same rules must hold on the VERIFY side too, or a token minted by a
// future careless caller would be honoured. Sign these by hand to prove it.
async function handSign(claims) {
  const payload = b64urlEncode(enc.encode(JSON.stringify(claims)));
  const key = await crypto.subtle.importKey(
    'raw', enc.encode(TEST_SECRET), { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);
  const mac = new Uint8Array(await crypto.subtle.sign('HMAC', key, enc.encode(payload)));
  return `${payload}.${b64urlEncode(mac)}`;
}
const base = { v: 1, e: 'neighbor@example.org', t: ISSUED, x: 0, n: 'AAAAAAAAAAAAAAAAAAAAAA' };

{
  const t = await handSign({ ...base, p: 'unsub', i: [], o: ['legislative', 'news-passive'] });
  const r = await verifyToken(TEST_SECRET, t, {
    purpose: PURPOSE_UNSUB, allowed: ALLOWED, now: ISSUED + 10 });
  check('a validly signed two-list unsub token is still refused',
        !r.ok && r.reason === 'bad_scope', r.reason);
}
{
  const t = await handSign({ ...base, p: 'unsub', i: ['legislative'], o: ['news-passive'] });
  const r = await verifyToken(TEST_SECRET, t, {
    purpose: PURPOSE_UNSUB, allowed: ALLOWED, now: ISSUED + 10 });
  check('an unsub token carrying an opt-in is refused', !r.ok, r.reason);
}
{
  const t = await handSign({ ...base, p: 'unsub', i: [], o: ['everyone'] });
  const r = await verifyToken(TEST_SECRET, t, {
    purpose: PURPOSE_UNSUB, allowed: ALLOWED, now: ISSUED + 10 });
  check('a signed token naming an unknown list is refused',
        !r.ok && r.reason === 'unknown_list', r.reason);
}
{
  // A caller that forgets to pass the allowlist must fail closed, not open.
  const r = await verifyToken(TEST_SECRET, unsubToken, {
    purpose: PURPOSE_UNSUB, allowed: [], now: ISSUED + 10 });
  check('an empty allowlist refuses everything', !r.ok, r.reason);
}
{
  const t = await handSign({ ...base, p: 'unsub', i: [], o: ['legislative'], v: 2 });
  const r = await verifyToken(TEST_SECRET, t, {
    purpose: PURPOSE_UNSUB, allowed: ALLOWED, now: ISSUED + 10 });
  check('a future version is refused rather than guessed at',
        !r.ok && r.reason === 'bad_version', r.reason);
}
{
  const t = await handSign({ ...base, p: 'unsub', i: [], o: ['legislative'], e: 'not-an-email' });
  const r = await verifyToken(TEST_SECRET, t, {
    purpose: PURPOSE_UNSUB, allowed: ALLOWED, now: ISSUED + 10 });
  check('a signed token with an implausible address is refused', !r.ok, r.reason);
}
{
  const t = await handSign({ ...base, p: 'unsub', i: [], o: 'legislative' });
  const r = await verifyToken(TEST_SECRET, t, {
    purpose: PURPOSE_UNSUB, allowed: ALLOWED, now: ISSUED + 10 });
  check('a string where a list array belongs is refused', !r.ok, r.reason);
}

// --- 6. expiry --------------------------------------------------------------
{
  const at = ISSUED + 48 * 3600;
  check('a confirm token is dead the second it expires',
        !(await verifyToken(TEST_SECRET, confirmToken, {
          purpose: PURPOSE_CONFIRM, allowed: ALLOWED, now: at })).ok);
  check('and stays dead',
        !(await verifyToken(TEST_SECRET, confirmToken, {
          purpose: PURPOSE_CONFIRM, allowed: ALLOWED, now: at + 86400 })).ok);
  check('but lives one second before',
        (await verifyToken(TEST_SECRET, confirmToken, {
          purpose: PURPOSE_CONFIRM, allowed: ALLOWED, now: at - 1 })).ok);
  const r = await verifyToken(TEST_SECRET, confirmToken, {
    purpose: PURPOSE_CONFIRM, allowed: ALLOWED, now: at });
  check('the refusal names expiry', r.reason === 'expired', r.reason);
}
check('an unsub token survives a decade',
      (await verifyToken(TEST_SECRET, unsubToken, {
        purpose: PURPOSE_UNSUB, allowed: ALLOWED, now: ISSUED + 10 * 365 * 86400 })).ok);

// A negative expiry must not read as "never expires".
{
  const t = await handSign({ ...base, p: 'unsub', i: [], o: ['legislative'], x: -1 });
  check('a negative expiry is refused, not treated as never',
        !(await verifyToken(TEST_SECRET, t, {
          purpose: PURPOSE_UNSUB, allowed: ALLOWED, now: ISSUED })).ok);
}

// --- 7. no secret and no capability in the artifact -------------------------
const fs = await import('node:fs/promises');
const tokenSrc = await fs.readFile(new URL('./_subscribe_token.js', import.meta.url), 'utf8');
check('the token module makes no network call', !/\bfetch\s*\(/.test(tokenSrc));
check('the token module names no endpoint', !tokenSrc.includes('api.resend.com'));
check('the token module holds no api key literal', !/\bre_[A-Za-z0-9]{8}/.test(tokenSrc));

for (const name of ['subscribe.js', 'confirm.js', 'unsubscribe.js', '_lists.js']) {
  const src = await fs.readFile(new URL(`./${name}`, import.meta.url), 'utf8');
  check(`${name} reads its secrets from env only`,
        !/\bre_[A-Za-z0-9]{8}/.test(src) && !/0x4AAAAAA/.test(src));
  check(`${name} references SUBSCRIBE_HMAC_KEY only through env`,
        !src.includes('SUBSCRIBE_HMAC_KEY') || /env\.SUBSCRIBE_HMAC_KEY/.test(src));
}

// The one Resend field this feature must never write. Setting the contact level
// `unsubscribed` flag would let one list's unsubscribe silently mute another,
// or let a re-subscribe override a global opt-out somebody set themselves.
const listsSrc = await fs.readFile(new URL('./_lists.js', import.meta.url), 'utf8');
check('no code path writes the global unsubscribed flag',
      !/unsubscribed\s*:/.test(listsSrc));
const subscribeSrc = await fs.readFile(new URL('./subscribe.js', import.meta.url), 'utf8');
check('subscribe.js writes no global unsubscribed flag',
      !/unsubscribed\s*:/.test(subscribeSrc));

// The confirm link must be pinned to the chapter's own origin, never taken from
// the request host.
check('the confirm link origin is pinned to https',
      subscribeSrc.includes('https://knoxvilledsa.org')
      && !/request\.headers\.get\(['"]host/i.test(subscribeSrc));

// The endpoint that anyone on the internet can reach must not be able to change
// anybody's subscription state. The only thing that may is a verified token.
// Comments are stripped first, because these files argue about the very calls
// they must not make, at length, and a prose mention is not a call.
const codeOnly = (src) => src.split('\n').filter((l) => !/^\s*\/\//.test(l)).join('\n');
check('subscribe.js cannot write topic state at all',
      !/\bsetTopics\b/.test(codeOnly(subscribeSrc))
      && !/\bensureContact\b/.test(codeOnly(subscribeSrc)));
check('subscribe.js writes no opt_out anywhere', !/opt_out/.test(codeOnly(subscribeSrc)));
{
  const urls = subscribeSrc.match(/https:\/\/api\.resend\.com[^\s'"`)]*/g) || [];
  check('subscribe.js names only the Resend SEND endpoint',
        urls.length === 1 && urls[0] === 'https://api.resend.com/emails', urls.join(' '));
}
for (const [name, src] of [['subscribe.js', subscribeSrc],
                           ['confirm.js', await fs.readFile(new URL('./confirm.js', import.meta.url), 'utf8')]]) {
  // A missing KV binding must be a configuration failure, never a silent
  // downgrade to no rate limiting and no single-use enforcement.
  check(`${name} refuses to run without the CONTACT_KV binding`,
        /!env\.CONTACT_KV/.test(src));
}

// --- 8. the address regex, against the Python senders -----------------------
// An address this side accepts but src/legislative_monitor/send_digest.py and
// src/dsa_news/send.py reject is worse than one refused at signup: it confirms,
// gets written as opted in, and is then skipped at every send forever, visible
// only as an anonymous count in a log. So this is a port of their _ADDR_RE:
//
//   ^[^@\s,;<>"]+@[^@\s,;<>"]+\.[A-Za-z]{2,}$
//
for (const good of [
  'neighbor@example.org',
  'a@b.co',
  'first.last+watch@mail.example.co.uk',
  "o'brien@example.org",
  'x_y-z@sub.domain.example',
]) {
  check(`a real address is accepted: ${good}`, isPlausibleEmail(good));
}
for (const bad of [
  'a,b@example.org',        // comma: Python rejects, the old JS regex did not
  'a;b@example.org',        // semicolon, same
  '<neighbor@example.org>', // angle brackets, as a mail client would paste them
  'neighbor@example.org>',
  '"quoted"@example.org',   // a quote, which the old regex also let through
  'neighbor@example.123',   // numeric TLD
  'neighbor@example.o',     // one-letter TLD
  'neighbor@example.org.',  // trailing dot
  'neighbor@example',       // no dot at all
  'neighbor@.org',
  '@example.org',
  'neighbor example@x.org', // space
  'neighbor@exam ple.org',
  '',
]) {
  check(`a malformed address is refused: ${JSON.stringify(bad)}`, !isPlausibleEmail(bad));
}
check('an over-long address is refused',
      !isPlausibleEmail(`${'a'.repeat(200)}@example.org`));

// --- 9. the endpoints, against the attack the review found ------------------
// THE BUG THIS SECTION EXISTS FOR. /api/subscribe used to write every requested
// topic as opt_out before any confirm click. Submitting the public form with a
// real subscriber's address and their list ticked therefore unsubscribed them
// on the spot, with no token and no proof of inbox access, going straight round
// the signed-token scheme that guards /api/unsubscribe.
//
// These run the real handlers with a fake env, a fake KV and a stubbed fetch.

const realFetch = globalThis.fetch;
let calls = [];

function stubFetch({ turnstile = true, sendOk = true } = {}) {
  calls = [];
  globalThis.fetch = async (url, init = {}) => {
    const href = String(url);
    const body = typeof init.body === 'string' ? init.body : String(init.body || '');
    calls.push({ url: href, method: (init.method || 'GET').toUpperCase(), body });
    if (href.includes('challenges.cloudflare.com')) {
      return new Response(JSON.stringify({ success: turnstile }), {
        status: 200, headers: { 'content-type': 'application/json' } });
    }
    if (href.includes('api.resend.com/emails')) {
      return new Response(JSON.stringify({ id: 'test' }), { status: sendOk ? 200 : 502 });
    }
    // Anything the handler sends at the contacts API succeeds, so a test that
    // asserts "no contact call happened" is asserting the absence of the call,
    // never a failure of it.
    return new Response(JSON.stringify({ data: [] }), { status: 200 });
  };
}

function fakeKV() {
  const store = new Map();
  return {
    store,
    async get(k) { return store.has(k) ? store.get(k) : null; },
    async put(k, v) { store.set(k, String(v)); },
  };
}

function envWith(kv, extra = {}) {
  return {
    TURNSTILE_SECRET: 'test-turnstile-secret',
    RESEND_API_KEY: 'test-sending-key',
    RESEND_CONTACTS_API_KEY: 'test-contacts-key',
    SUBSCRIBE_HMAC_KEY: TEST_SECRET,
    RESEND_TOPIC_LEGISLATIVE: 'topic_legislative',
    RESEND_TOPIC_NEWS_AGGRESSIVE: 'topic_news_aggressive',
    RESEND_TOPIC_NEWS_PASSIVE: 'topic_news_passive',
    SITE_ORIGIN: 'https://knoxvilledsa.org',
    CONTACT_KV: kv,
    ...extra,
  };
}

function subscribeRequest(fields, ip = '203.0.113.7') {
  return new Request('https://knoxvilledsa.org/api/subscribe', {
    method: 'POST',
    headers: {
      accept: 'application/json',
      'content-type': 'application/x-www-form-urlencoded',
      'CF-Connecting-IP': ip,
    },
    body: new URLSearchParams({ 'cf-turnstile-response': 'test-token', ...fields }),
  });
}

const contactCalls = () => calls.filter((c) => c.url.includes('api.resend.com/contacts'));
const sendCalls = () => calls.filter((c) => c.url.includes('api.resend.com/emails'));

// 9a. The attack itself. victim@example.org is, as far as this endpoint knows,
// already subscribed to Legislative Watch. A stranger submits the form with
// their address and that list ticked.
{
  stubFetch();
  const env = envWith(fakeKV());
  const res = await subscribePost({
    request: subscribeRequest({ email: 'victim@example.org', legislative_watch: 'on' }),
    env,
  });
  const body = await res.json();
  check('a stranger submitting somebody else’s address still gets a bland ok',
        res.status === 200 && body.ok === true, `${res.status} ${JSON.stringify(body)}`);
  check('THE FIX: no contact-store call is made before the confirm click',
        contactCalls().length === 0,
        contactCalls().map((c) => `${c.method} ${c.url} ${c.body}`).join(' | '));
  check('THE FIX: nothing anywhere in the request writes opt_out',
        !calls.some((c) => c.body.includes('opt_out')),
        calls.map((c) => c.body).join(' | '));
  check('exactly one email is sent, to the submitted address and nobody else',
        sendCalls().length === 1
        && JSON.parse(sendCalls()[0].body).to.length === 1
        && JSON.parse(sendCalls()[0].body).to[0] === 'victim@example.org');
  check('the full-access contacts key is never spent on this path',
        !calls.some((c) => c.body.includes('test-contacts-key')));
}

// 9b. Same for the News Watch radio, which carries a paired opt-out. That
// opt-out must not reach Resend either until the token that names it is
// verified: someone on the aggressive list must not be knocked off it by a
// stranger picking passive on their behalf.
{
  stubFetch();
  const env = envWith(fakeKV());
  const res = await subscribePost({
    request: subscribeRequest({ email: 'victim@example.org', news_watch: 'passive' }),
    env,
  });
  check('a news-mode switch also writes nothing before the click',
        res.status === 200 && contactCalls().length === 0);
}

// 9c. A missing CONTACT_KV binding is a deployment mistake and must be loud.
// Before the fix both endpoints silently skipped the throttle and the
// single-use nonce burn and carried on.
{
  stubFetch();
  const env = envWith(fakeKV());
  delete env.CONTACT_KV;
  const res = await subscribePost({
    request: subscribeRequest({ email: 'neighbor@example.org', legislative_watch: 'on' }),
    env,
  });
  const body = await res.json();
  check('subscribe refuses when CONTACT_KV is unbound',
        res.status === 503 && body.error === 'not_configured',
        `${res.status} ${JSON.stringify(body)}`);
  check('and sends nothing at all in that state', calls.length === 0);
}

// 9d. One confirm email per address per hour, whoever asks and from wherever.
{
  stubFetch();
  const env = envWith(fakeKV());
  const first = await subscribePost({
    request: subscribeRequest({ email: 'neighbor@example.org', legislative_watch: 'on' }, '203.0.113.1'),
    env,
  });
  const second = await subscribePost({
    request: subscribeRequest({ email: 'neighbor@example.org', legislative_watch: 'on' }, '198.51.100.2'),
    env,
  });
  const body = await second.json();
  check('the first signup for an address is accepted', first.status === 200);
  check('a second one within the window is refused, even from a new IP',
        second.status === 429 && body.error === 'rate_limited',
        `${second.status} ${JSON.stringify(body)}`);
  check('so only one confirm email was ever sent', sendCalls().length === 1);
  check('and KV holds no readable address, only a keyed digest',
        [...env.CONTACT_KV.store.keys()].every((k) => !k.includes('neighbor@example.org')),
        [...env.CONTACT_KV.store.keys()].join(' '));
}

// 9e. The tightened address check is enforced by the endpoint, not just by the
// browser, and it is refused before Turnstile or Resend is touched.
{
  stubFetch();
  const env = envWith(fakeKV());
  const res = await subscribePost({
    request: subscribeRequest({ email: 'neighbor@example.o', legislative_watch: 'on' }),
    env,
  });
  const body = await res.json();
  check('an address the Python senders would skip is refused at signup',
        res.status === 400 && body.error === 'bad_email',
        `${res.status} ${JSON.stringify(body)}`);
  check('and nothing was called on its behalf', calls.length === 0);
}

// 9f. The other half of the fix: the confirm click still works, and it is now
// the ONLY thing that writes subscription state. A new address must end up
// opted in exactly once, on exactly the lists the signed token names.
{
  stubFetch();
  const env = envWith(fakeKV());
  const token = await mintToken(TEST_SECRET, {
    purpose: PURPOSE_CONFIRM,
    email: 'newcomer@example.org',
    optIn: ['legislative', 'news-passive'],
    optOut: ['news-aggressive'],
    allowed: ALLOWED,
  });
  const res = await confirmGet({
    request: new Request(`https://knoxvilledsa.org/api/confirm?token=${encodeURIComponent(token)}`,
                         { headers: { accept: 'application/json' } }),
    env,
  });
  const body = await res.json();
  check('a valid confirm click succeeds', res.status === 200 && body.ok === true,
        `${res.status} ${JSON.stringify(body)}`);
  const patch = contactCalls().find((c) => c.method === 'PATCH');
  check('the confirm click is what writes the topics', Boolean(patch));
  if (patch) {
    const written = JSON.parse(patch.body);
    check('it opts in to exactly the two lists the token names',
          written.filter((e) => e.subscription === 'opt_in')
            .map((e) => e.id).sort().join(',') === 'topic_legislative,topic_news_passive',
          patch.body);
    check('and opts out of the unpicked news mode, and nothing else',
          written.filter((e) => e.subscription === 'opt_out')
            .map((e) => e.id).join(',') === 'topic_news_aggressive',
          patch.body);
    check('it never writes the global unsubscribed flag',
          !patch.body.includes('unsubscribed'), patch.body);
  }

  // Single use, which only works because CONTACT_KV is now guaranteed present.
  const claims = JSON.parse(new TextDecoder().decode(b64urlDecode(token.split('.')[0])));
  const nonceKey = `sub:used:${claims.n}`;
  check('the nonce was burned', env.CONTACT_KV.store.has(nonceKey));
  // Age it past the scanner-prefetch grace window, then replay.
  env.CONTACT_KV.store.set(nonceKey, String(Math.floor(Date.now() / 1000) - 4000));
  stubFetch();
  const replay = await confirmGet({
    request: new Request(`https://knoxvilledsa.org/api/confirm?token=${encodeURIComponent(token)}`,
                         { headers: { accept: 'application/json' } }),
    env,
  });
  check('a stale replay of a used confirm link is refused',
        replay.status === 409, String(replay.status));
  check('and it touches the contact store on the way to refusing nobody',
        contactCalls().length === 0);
}

// 9g. Confirm fails closed without KV too, or single use was never enforced.
{
  stubFetch();
  const env = envWith(fakeKV());
  delete env.CONTACT_KV;
  const token = await mintToken(TEST_SECRET, {
    purpose: PURPOSE_CONFIRM, email: 'newcomer@example.org',
    optIn: ['legislative'], optOut: [], allowed: ALLOWED,
  });
  const res = await confirmGet({
    request: new Request(`https://knoxvilledsa.org/api/confirm?token=${encodeURIComponent(token)}`,
                         { headers: { accept: 'application/json' } }),
    env,
  });
  const body = await res.json();
  check('confirm refuses when CONTACT_KV is unbound',
        res.status === 503 && body.error === 'not_configured',
        `${res.status} ${JSON.stringify(body)}`);
  check('and writes nothing in that state', contactCalls().length === 0);
}

globalThis.fetch = realFetch;

// --- 10. odds and ends ------------------------------------------------------
check('normalizeEmail lowercases and trims', normalizeEmail('  A@B.CO ') === 'a@b.co');
check('normalizeEmail survives null', normalizeEmail(null) === '');
check('every list slug is url and header safe',
      ALLOWED.every((s) => /^[a-z0-9-]+$/.test(s)));

if (failures) {
  console.error(`\n${failures} failure(s). Do NOT publish.`);
  process.exit(1);
}
console.log('_subscribe_token.js: vectors, forgery, purpose, list scope, expiry and capability all pass');
